#!/bin/tcsh
echo "I need to INSERT an INITIAL BALANCE"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf<< EOF
use managementoverview;
truncate cashflows;
commit;
EOF
echo "Chargement de CA20150719"
cd $RES/Perl/
perl -w $RES/Perl/extractCashflows $RES/Data/CA20150719_1114.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"   managementoverview $RES/Datavalidated/cashflows.csv
echo "Chargement de CA20121108"
#perl -w $RES/Perl/extractCashflows $RES/Data/CA20121108_2009.txt 2012
#more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
#mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv
echo "Chargement de CA20131029"
#perl -w $RES/Perl/extractCashflows $RES/Data/CA20131029_1236.txt 2013
#more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
#mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv
echo "Chargement de CA20150724_1659.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20150724_1659.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv
cp -p $RES/Datavalidated/cashflows-cmb.csv $RES/Datavalidated/cashflows.csv
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf -D managementoverview < $RES/Sql/MysqlUpdateCategories.sql
echo "Chargement de CA20150801_0844.txt"
#sed "s/\$//g" $RES/Data/CA20150801_0844.txt 
#sed "s/ //g" $RES/Data/CA20150801_0844.txt 
#sed "s/é/e/g" $RES/Data/CA20150801_0844.txt 
perl -w $RES/Perl/extractCashflows $RES/Data/CA20150801_0844.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20150823_0102.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20150823_0102.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20151029_0102.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20151027_1739.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

#echo "Chargement de CA20151027_1739.txt"
#perl -w $RES/Perl/extractCashflows $RES/Data/CA20151027_1739.txt 2015
#mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20151128_2133.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20151128_2133.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20151222_1615.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20151222_1615.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160103_2243.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160103_2243.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160403_0935.txt"
#sed "s/\$//g" $RES/Data/CA20160403_0935.txt > $RES/Data/CA20160403_0935.txt
#sed "s/ //g" $RES/Data/CA20160403_0935.txt > $RES/Data/CA20160403_0935.txt
#sed "s/é/e/g" $RES/Data/CA20160403_0935.txt > $RES/Data/CA20160403_0935.txt
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160403_0935.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160108_1102_2015.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160108_1102_2015.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160108_1102_2016.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160108_1102_2016.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160112_1933_2015.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160112_1933_2015.txt 2015
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160112_1933_2016.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160112_1933_2016.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160417_1907.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160417_1907.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160808_1522.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160808_1522.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20160829_1305.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20160829_1305.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv

echo "Chargement de CA20161008_2224.txt"
perl -w $RES/Perl/extractCashflows $RES/Data/CA20161008_2224.txt 2016
more $RES/Datavalidated/cashflows.csv  | sed s/\,/./g > $RES/Datavalidated/cashflows_final.csv
mysqlimport --defaults-extra-file=$RES_HOME/MyData/config.cnf --ignore-lines=1 --local --fields-terminated-by=";"  managementoverview $RES/Datavalidated/cashflows.csv
