#!/bin/tcsh
set user1 = "root"
#echo $user1
#echo $PATH
#echo $shell
set RESEARCH = $RES 
set dropfile = $RES/Sql/Mysql-drop.sql
#now=$(date +"%Y-%m-%d")
#echo "Current diretory :" $RESEARCH
set SQLDIR = $RESEARCH/Sql/
#echo "Sql directory :" $SQLDIR
echo "STEP - Database construction..."
#pwd
echo "STEP - We drop everything"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf -D managementoverview < $RES/Sql/Mysql-drop.sql
echo "STEP - We build also the tasks"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf -D managementoverview < $RES/Sql/createTasks.sql
echo "STEP - We build also the burndown"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf -D managementoverview < $RES/Sql/createBurndown.sql
echo "STEP - We build also the kapital"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf -D managementoverview < $RES/Sql/createKapital.sql
echo "STEP - We rebuild it"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf -D managementoverview < $RES/Sql/Mysql-create.sql
echo "STEP - We check that everything is ok"
mysql --defaults-extra-file=$RES_HOME/MyData/config.cnf << EOF
use managementoverview;
show tables;
EOF
